project_id      = "hansroslinger-468011"
region          = "australia-southeast1"
repository_name = "cloud-run-repo-au"
bucket_name     = "hansroslinger-assets-au"
bucket_location = "australia-southeast1"
