name: Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          install_components: 'beta'

      - name: Build and Push Docker image
        run: |
          IMAGE="gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}"
          gcloud builds submit --tag $IMAGE .

      - name: Deploy to Cloud Run
        run: |
          IMAGE="gcr.io/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}"
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image $IMAGE \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated
