name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (defaults to commit SHA)'
        required: false
        default: ''

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest
    env:
      REGION: us-central1
      GAR_REGION: australia-southeast1
      BUCKET_NAME: hansroslinger-assets-us

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          install_components: "gcloud"

      - name: Configure Docker to use gcloud as credential helper
        run: gcloud auth configure-docker ${{ env.GAR_REGION }}-docker.pkg.dev

      - name: Build and push Docker image
        run: |
          IMAGE="${{ env.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}"
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image "${{ env.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/${{ secrets.ARTIFACT_REGISTRY_REPO }}/${{ secrets.CLOUD_RUN_SERVICE }}:${{ github.sha }}" \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --port=${{ secrets.PORT }} \
            --set-env-vars "MONGO_URL=${{ secrets.MONGO_URL }},LOCATION=${{ env.REGION }},BUCKET_NAME=${{ env.BUCKET_NAME }}" 