name: EsLint

on:
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HansRoslinger
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'
      - run: npm install
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: .
