name: Prettier

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  prettier:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: HansRoslinger
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.5
        with:
          prettier_options: --write **/*.{ts,tsx}
  
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Prettified Code" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.head_ref || github.ref_name }}