name: Validate PR Template

on:
  pull_request:
    branches: [main]

jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR template completeness
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";

            const sections = {
              Changes: /## Changes\s*([\s\S]*?)(?=\n## |$)/i,
              Description: /## Description\s*([\s\S]*?)(?=\n## |$)/i,
              Checklist: /## Checklist\s*([\s\S]*?)(?=\n## |$)/i,
            };

            for (const [section, regex] of Object.entries(sections)) {
              const match = body.match(regex);
              if (!match || match[1].trim().length === 0) {
                core.setFailed(`❌ The "${section}" section is missing or empty.`);
              }
            }
